  
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: run tests
      uses: ReactiveCircus/android-emulator-runner@v2.15.0
      with:
        api-level: 29
        script: ./gradlew connectedCheck
        
